// Mocks generated by Mockito 5.4.6 from annotations
// in news_app_clean_architecture/test/features/auth/domain/usecases/author_profile_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app_clean_architecture/core/resources/data_state.dart'
    as _i2;
import 'package:news_app_clean_architecture/features/auth/domain/entities/user.entity.dart'
    as _i8;
import 'package:news_app_clean_architecture/features/auth/domain/entities/user_profile.entity.dart'
    as _i5;
import 'package:news_app_clean_architecture/features/auth/domain/repository/auth_repository.dart'
    as _i7;
import 'package:news_app_clean_architecture/features/auth/domain/repository/user_profile_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRepository extends _i1.Mock
    implements _i3.UserProfileRepository {
  MockUserProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<void>> createUserProfile(
          _i5.UserProfileEntity? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserProfile,
          [profile],
        ),
        returnValue:
            _i4.Future<_i2.DataState<void>>.value(_FakeDataState_0<void>(
          this,
          Invocation.method(
            #createUserProfile,
            [profile],
          ),
        )),
      ) as _i4.Future<_i2.DataState<void>>);

  @override
  _i4.Future<_i2.DataState<_i5.UserProfileEntity?>> getAuthorProfile(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthorProfile,
          [userId],
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.UserProfileEntity?>>.value(
            _FakeDataState_0<_i5.UserProfileEntity?>(
          this,
          Invocation.method(
            #getAuthorProfile,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.UserProfileEntity?>>);

  @override
  _i4.Future<_i2.DataState<String?>> uploadAvatar(
    String? userId,
    _i6.File? avatarFile,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [
            userId,
            avatarFile,
          ],
        ),
        returnValue:
            _i4.Future<_i2.DataState<String?>>.value(_FakeDataState_0<String?>(
          this,
          Invocation.method(
            #uploadAvatar,
            [
              userId,
              avatarFile,
            ],
          ),
        )),
      ) as _i4.Future<_i2.DataState<String?>>);

  @override
  _i4.Future<_i2.DataState<_i5.UserProfileEntity>> updateUserProfile({
    required String? userId,
    required String? displayName,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {
            #userId: userId,
            #displayName: displayName,
            #photoUrl: photoUrl,
          },
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.UserProfileEntity>>.value(
            _FakeDataState_0<_i5.UserProfileEntity>(
          this,
          Invocation.method(
            #updateUserProfile,
            [],
            {
              #userId: userId,
              #displayName: displayName,
              #photoUrl: photoUrl,
            },
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.UserProfileEntity>>);

  @override
  void invalidateAuthorProfile(String? userId) => super.noSuchMethod(
        Invocation.method(
          #invalidateAuthorProfile,
          [userId],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i8.UserEntity?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i8.UserEntity?>.empty(),
      ) as _i4.Stream<_i8.UserEntity?>);

  @override
  _i4.Future<_i2.DataState<_i8.UserEntity>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.DataState<_i8.UserEntity>>.value(
            _FakeDataState_0<_i8.UserEntity>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i8.UserEntity>>);

  @override
  _i4.Future<_i2.DataState<_i8.UserEntity>> register({
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i4.Future<_i2.DataState<_i8.UserEntity>>.value(
            _FakeDataState_0<_i8.UserEntity>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #password: password,
              #displayName: displayName,
            },
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i8.UserEntity>>);

  @override
  _i4.Future<_i2.DataState<void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue:
            _i4.Future<_i2.DataState<void>>.value(_FakeDataState_0<void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DataState<void>>);

  @override
  _i4.Future<_i2.DataState<void>> deleteCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteCurrentUser,
          [],
        ),
        returnValue:
            _i4.Future<_i2.DataState<void>>.value(_FakeDataState_0<void>(
          this,
          Invocation.method(
            #deleteCurrentUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DataState<void>>);

  @override
  _i4.Future<_i2.DataState<_i8.UserEntity?>> updateCurrentUserProfile({
    String? displayName,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCurrentUserProfile,
          [],
          {
            #displayName: displayName,
            #photoUrl: photoUrl,
          },
        ),
        returnValue: _i4.Future<_i2.DataState<_i8.UserEntity?>>.value(
            _FakeDataState_0<_i8.UserEntity?>(
          this,
          Invocation.method(
            #updateCurrentUserProfile,
            [],
            {
              #displayName: displayName,
              #photoUrl: photoUrl,
            },
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i8.UserEntity?>>);

  @override
  _i4.Future<_i2.DataState<_i8.UserEntity?>> getCurrentUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.DataState<_i8.UserEntity?>>.value(
            _FakeDataState_0<_i8.UserEntity?>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i8.UserEntity?>>);
}
