// Mocks generated by Mockito 5.4.6 from annotations
// in news_app_clean_architecture/test/features/news/domain/usecases/get_user_articles_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app_clean_architecture/core/resources/data_state.dart'
    as _i2;
import 'package:news_app_clean_architecture/features/news/domain/entities/article.entity.dart'
    as _i5;
import 'package:news_app_clean_architecture/features/news/domain/repository/user_article_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserArticleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserArticleRepository extends _i1.Mock
    implements _i3.UserArticleRepository {
  MockUserArticleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<List<_i5.ArticleEntity>>> getAllUserArticles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllUserArticles,
          [],
        ),
        returnValue: _i4.Future<_i2.DataState<List<_i5.ArticleEntity>>>.value(
            _FakeDataState_0<List<_i5.ArticleEntity>>(
          this,
          Invocation.method(
            #getAllUserArticles,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DataState<List<_i5.ArticleEntity>>>);

  @override
  _i4.Future<_i2.DataState<List<_i5.ArticleEntity>>> getUserArticles(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserArticles,
          [userId],
        ),
        returnValue: _i4.Future<_i2.DataState<List<_i5.ArticleEntity>>>.value(
            _FakeDataState_0<List<_i5.ArticleEntity>>(
          this,
          Invocation.method(
            #getUserArticles,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.DataState<List<_i5.ArticleEntity>>>);

  @override
  _i4.Future<_i2.DataState<void>> createUserArticle(
    _i5.ArticleEntity? article, {
    _i6.File? imageFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserArticle,
          [article],
          {#imageFile: imageFile},
        ),
        returnValue:
            _i4.Future<_i2.DataState<void>>.value(_FakeDataState_0<void>(
          this,
          Invocation.method(
            #createUserArticle,
            [article],
            {#imageFile: imageFile},
          ),
        )),
      ) as _i4.Future<_i2.DataState<void>>);

  @override
  _i4.Future<_i2.DataState<void>> updateUserArticle(
    _i5.ArticleEntity? article, {
    _i6.File? imageFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserArticle,
          [article],
          {#imageFile: imageFile},
        ),
        returnValue:
            _i4.Future<_i2.DataState<void>>.value(_FakeDataState_0<void>(
          this,
          Invocation.method(
            #updateUserArticle,
            [article],
            {#imageFile: imageFile},
          ),
        )),
      ) as _i4.Future<_i2.DataState<void>>);

  @override
  _i4.Future<_i2.DataState<void>> deleteUserArticle(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserArticle,
          [articleId],
        ),
        returnValue:
            _i4.Future<_i2.DataState<void>>.value(_FakeDataState_0<void>(
          this,
          Invocation.method(
            #deleteUserArticle,
            [articleId],
          ),
        )),
      ) as _i4.Future<_i2.DataState<void>>);
}
