// Mocks generated by Mockito 5.4.6 from annotations
// in news_app_clean_architecture/test/features/news/presentation/bloc/author_avatar_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app_clean_architecture/core/resources/data_state.dart'
    as _i2;
import 'package:news_app_clean_architecture/features/auth/domain/entities/user_profile.entity.dart'
    as _i5;
import 'package:news_app_clean_architecture/features/auth/domain/usecases/get_author_profile.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAuthorProfile].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAuthorProfile extends _i1.Mock implements _i3.GetAuthorProfile {
  MockGetAuthorProfile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<_i5.UserProfileEntity?>> call(
          {_i3.GetAuthorProfileParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.UserProfileEntity?>>.value(
            _FakeDataState_0<_i5.UserProfileEntity?>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.UserProfileEntity?>>);
}
