// Mocks generated by Mockito 5.4.6 from annotations
// in news_app_clean_architecture/test/features/daily_news/data/repository/article_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app_clean_architecture/features/daily_news/data/data_sources/local/app_database.dart'
    as _i8;
import 'package:news_app_clean_architecture/features/daily_news/data/data_sources/local/DAO/article_dao.dart'
    as _i3;
import 'package:news_app_clean_architecture/features/daily_news/data/data_sources/remote/news_api_service.dart'
    as _i6;
import 'package:news_app_clean_architecture/features/daily_news/data/models/article.dart'
    as _i7;
import 'package:retrofit/retrofit.dart' as _i2;
import 'package:sqflite/sqflite.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArticleDao_1 extends _i1.SmartFake implements _i3.ArticleDao {
  _FakeArticleDao_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamController_2<T> extends _i1.SmartFake
    implements _i4.StreamController<T> {
  _FakeStreamController_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseExecutor_3 extends _i1.SmartFake
    implements _i5.DatabaseExecutor {
  _FakeDatabaseExecutor_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NewsApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsApiService extends _i1.Mock implements _i6.NewsApiService {
  MockNewsApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<List<_i7.ArticleModel>>> getNewsArticles({
    String? apiKey,
    String? country,
    String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNewsArticles,
          [],
          {
            #apiKey: apiKey,
            #country: country,
            #category: category,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<List<_i7.ArticleModel>>>.value(
            _FakeHttpResponse_0<List<_i7.ArticleModel>>(
          this,
          Invocation.method(
            #getNewsArticles,
            [],
            {
              #apiKey: apiKey,
              #country: country,
              #category: category,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<List<_i7.ArticleModel>>>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i8.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ArticleDao get articleDAO => (super.noSuchMethod(
        Invocation.getter(#articleDAO),
        returnValue: _FakeArticleDao_1(
          this,
          Invocation.getter(#articleDAO),
        ),
      ) as _i3.ArticleDao);

  @override
  _i4.StreamController<String> get changeListener => (super.noSuchMethod(
        Invocation.getter(#changeListener),
        returnValue: _FakeStreamController_2<String>(
          this,
          Invocation.getter(#changeListener),
        ),
      ) as _i4.StreamController<String>);

  @override
  _i5.DatabaseExecutor get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabaseExecutor_3(
          this,
          Invocation.getter(#database),
        ),
      ) as _i5.DatabaseExecutor);

  @override
  set changeListener(_i4.StreamController<String>? value) => super.noSuchMethod(
        Invocation.setter(
          #changeListener,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set database(_i5.DatabaseExecutor? value) => super.noSuchMethod(
        Invocation.setter(
          #database,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ArticleDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleDao extends _i1.Mock implements _i3.ArticleDao {
  MockArticleDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> insertArticle(_i7.ArticleModel? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertArticle,
          [article],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteArticle(_i7.ArticleModel? articleModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteArticle,
          [articleModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.ArticleModel>> getArticles() => (super.noSuchMethod(
        Invocation.method(
          #getArticles,
          [],
        ),
        returnValue:
            _i4.Future<List<_i7.ArticleModel>>.value(<_i7.ArticleModel>[]),
      ) as _i4.Future<List<_i7.ArticleModel>>);
}
