// Mocks generated by Mockito 5.4.6 from annotations
// in news_app_clean_architecture/test/features/news/data/repository/user_article_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app_clean_architecture/features/news/data/data_sources/remote/user_articles_firebase_service.dart'
    as _i3;
import 'package:news_app_clean_architecture/features/news/data/models/article.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDocumentReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserArticlesFirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserArticlesFirebaseService extends _i1.Mock
    implements _i3.UserArticlesFirebaseService {
  @override
  _i4.Future<String?> uploadThumbnail(_i5.File? imageFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadThumbnail,
          [imageFile],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<_i2.DocumentReference<Map<String, dynamic>>> createUserArticle(
          _i6.ArticleModel? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserArticle,
          [article],
        ),
        returnValue:
            _i4.Future<_i2.DocumentReference<Map<String, dynamic>>>.value(
                _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #createUserArticle,
            [article],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DocumentReference<Map<String, dynamic>>>.value(
                _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #createUserArticle,
            [article],
          ),
        )),
      ) as _i4.Future<_i2.DocumentReference<Map<String, dynamic>>>);
}
