// Mocks generated by Mockito 5.4.6 from annotations
// in news_app_clean_architecture/test/features/daily_news/presentation/bloc/local_article_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app_clean_architecture/features/daily_news/domain/entities/article.dart'
    as _i4;
import 'package:news_app_clean_architecture/features/daily_news/domain/usecases/get_saved_article.dart'
    as _i2;
import 'package:news_app_clean_architecture/features/daily_news/domain/usecases/remove_article.dart'
    as _i6;
import 'package:news_app_clean_architecture/features/daily_news/domain/usecases/save_article.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetSavedArticleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSavedArticleUseCase extends _i1.Mock
    implements _i2.GetSavedArticleUseCase {
  MockGetSavedArticleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ArticleEntity>> call({dynamic params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue:
            _i3.Future<List<_i4.ArticleEntity>>.value(<_i4.ArticleEntity>[]),
      ) as _i3.Future<List<_i4.ArticleEntity>>);
}

/// A class which mocks [SaveArticleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveArticleUseCase extends _i1.Mock
    implements _i5.SaveArticleUseCase {
  MockSaveArticleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call({_i4.ArticleEntity? params}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [RemoveArticleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveArticleUseCase extends _i1.Mock
    implements _i6.RemoveArticleUseCase {
  MockRemoveArticleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call({_i4.ArticleEntity? params}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
